export const types = Object.freeze({
    //Async
    FETCH_PERSONES_ASYNC:  'FETCH_PERSONES_ASYNC',
    SEARCH_PERSONES_ASYNC: 'SEARCH_PERSONES_ASYNC',
    FETCH_PERSON_ASYNC:    'FETCH_PERSON_ASYNC',

    //Sync
    FILL_PERSONES:  'FILL_PERSONES',
    FILL_PERSON:    'FILL_PERSON',
    FILL_FILMS:     'FILL_FILMS',
    FILL_SPECIES:   'FILL_SPECIES',
    FILL_VEHICLES:  'FILL_VEHICLES',
    FILL_STARSHIPS: 'FILL_STARSHIPS',

    CLEAR_PERSON: 'CLEAR_PERSON',
});
